apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/pierre-anchien/catalog-service:k8s?ref=sha256:0401d6af7e3cf2183403e3c1274ad59e72feb470580a9906e931f2b9cbd4ebe1

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/pierre-anchien/catalog-service
  newTag: sha256:0401d6af7e3cf2183403e3c1274ad59e72feb470580a9906e931f2b9cbd4ebe1

replicas:
- count: 2
  name: catalog-service
